---
- name: Stopping old app
  shell: "kill -9 $(cat app/app.pid)"
  ignore_errors: yes

- name: Removing app dir
  file:
    path: /home/ec2-user/app
    state: absent

- name: Creating app dir
  file:
    path: /home/ec2-user/app
    state: directory
    mode: '0777'

- name: Download app.js from Nexus
  get_url:
    url: "{{ NEXUS_REPOSITORY_URL }}/microservicenodejs/{{ VERSION }}/app.js"
    dest: /home/ec2-user/app/
    mode: 0755
    force: yes

- name: Download app from Artifactory
  get_url:
    dest: /home/ec2-user/app/
    url: "{{ ARTIFACTORY_REPOSITORY_URL }}/generic-local/{{ VERSION }}/app.js"
    headers: 
      X-JFrog-Art-Api: "{{ ARTIFACTORY_API_KEY }}"
    mode: 0755
    force: yes

- name: Starting app - app.js
  shell: "nohup node app.js > /dev/null 2>&1 & echo $! > app.pid"
  async: 10
  poll: 0
  args:
    chdir: /home/ec2-user/app/
