---
- set_fact:
    repository: {{ REPOSITORY }}

- name: Stopping old app
  shell: "kill -9 $(cat app/app.pid)"
  ignore_errors: yes

- name: Removing app dir
  file:
    path: /home/ec2-user/app
    state: absent

- name: Creating app dir
  file:
    path: /home/ec2-user/app
    state: directory
    mode: '0777'

- name: Download app from Nexus
  when: repository == 'NEXUS'
  maven_artifact:
   dest: "/home/ec2-user/app/microservice-java-{{ VERSION }}.jar"
   group_id: com.example
   artifact_id: microservice-java
   extension: "jar"
   repository_url: "{{ NEXUS_REPOSITORY_URL }}/microservice-java"
   username: "{{ NEXUS_USERNAME }}"
   password: "{{ NEXUS_PASSWORD }}" 
   keep_name: yes
   version: "{{ VERSION }}"

- name: Download app from Artifactory
  when: repository == 'ARTIFACTORY'
  get_url:
    dest: /home/ec2-user/app/
    url: "{{ ARTIFACTORY_REPOSITORY_URL }}/libs-release-local/com/mycompany/microservice-java/microservice-java/{{ VERSION }}/microservice-java-{{ VERSION }}.jar"
    headers: 
      X-JFrog-Art-Api: "{{ ARTIFACTORY_API_KEY }}"
    mode: 0755
    force: yes

- name: Starting app - app.jar
  shell: "nohup java -jar app.jar > /dev/null 2>&1 & echo $! > app.pid"
  async: 10
  poll: 0
  args:
    chdir: /home/ec2-user/app/
